### ISSUE TITLE
No build from source

### ISSUE THREAD

**Issue by facastagnini** [infertux/chef-bitcoin#1]
Hi there. I am installing a full bitcoin node on a raspberry pi, and since I couldn't find a binary I am compiling from source.

You can see a quick draft here: https://github.com/facastagnini/raspberry-bitcoin/blob/master/cookbooks/raspberry-bitcoin/recipes/bitcoin-core.rb

I can prepare a nice PR if you are interested in merging it :)

**Comment by infertux** [comment]
Hi @facastagnini,

Yes please! I'm definitely interested.

I had to compile it by hand a while ago to run on an ARM architecture and having a Chef cookbook doing it would have saved me some time ;)
